name: coffee
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_staggered_grid_view: ^0.4.1
  image_picker: ^0.8.4+8
  image_cropper: ^1.5.0
  intl: ^0.17.0
  provider: ^6.0.0
  path_provider: ^2.0.2
  rxdart: ^0.27.2
  shared_preferences: ^2.0.9
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - lib/data/lang/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 800
